name: List Secrets
on: workflow_dispatch

jobs:
  list-secrets-1:
    runs-on: ubuntu-latest
    steps:
      - name: List Secrets
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          for secret_name in $(echo $SECRETS | jq -r 'keys[]'); do
            echo "Incoming ${secret_name}";
            if [[ $secret_name =~ MY_SECRET_* ]]; then
              secret_value=$(echo $SECRETS | jq -r ".[\"${secret_name}\"]" | sed 's/./& /g');
              echo "Adding secret ${secret_name} as environment variable";
              echo "${secret_name} = ${secret_value}";
            fi;
          done
          unset SECRETS
