name: List Secrets
on: workflow_dispatch

jobs:
  list-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: List Secrets
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          echo "" > output.txt
          for secret_name in $(echo "$SECRETS" | jq -r 'keys[]'); do
             echo "${secret_name}: ${{ secrets[secret_name] }}" >> output.txt
          done
          cat output.txt;
