name: List Secrets
on: workflow_dispatch

jobs:
  list-secrets-1:
    runs-on: ubuntu-latest
    steps:
      - name: List Secrets
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          echo "" > output.txt
          for secret_name in $(echo $SECRETS | jq -r 'keys[]'); do
            secret_value=$(echo $SECRETS | jq -r ".[\"${secret_name}\"]")
            echo "Adding secret ${secret_name} as environment variable"
            echo "${secret_name}=${secret_value}" >> $GITHUB_ENV
          done
          cat output.txt;
      - name: Print Secrets
        run: |
          for v in `env | grep '^MY'`; do name=`echo $v| cut -d'=' -f1`; value=`echo $v | cut -d'=' -f2`; echo "$value" > "$name"; done
          ls;
          cat MY_SECRET_TEST_1 | sed 's/./& /g'
